using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BulletSponer : MonoBehaviour
{
    public GameObject bulletPrefab;
    public float spawnRoteMin = 0.5f;
    public float spawnRoteMax = 3f;

    Transform target;
    float spawnRate;
    float timeAfterSpawn;

    // Start is called before the first frame update
    void Start()
    {
        timeAfterSpawn = 0f;
        spawnRate = Random.Range(spawnRoteMin, spawnRoteMax);
        target = FindObjectOfType<PlayerController>().transform;
    }

    // Update is called once per frame
    void Update()
    {
        timeAfterSpawn += Time.deltaTime;

        if(timeAfterSpawn >= spawnRate)
        {
            timeAfterSpawn = 0f;

            GameObject bullet = Instantiate(bulletPrefab, transform.position, transform.rotation);
            bullet.transform.LookAt(target);

            spawnRate = Random.Range(spawnRoteMin, spawnRoteMax);
        }
        
    }
}
